name: CI

on:
  push:
    branches: [ main, master, "**" ]
  pull_request:
    branches: [ main, master, "**" ]

permissions:
  contents: read

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          check-latest: true

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Ensure go.mod is tidy
        run: |
          go mod tidy
          git diff --exit-code -- go.mod go.sum

      - name: Build library layer
        run: go build ./internal

      - name: Build CLI
        run: go build .

      - name: Unit tests (internal only)
        run: go test -v ./internal
